# Site Settings
locale                   : "en-US"
title                    : "Nathan Sunday"
title_separator          : "-"
name                     : &name "Nathan Sunday"
description              : &description "Personal website of Nathan Sunday, PhD candidate in Economics at the University of Michigan."
url                      : https://nathan-sunday.github.io  # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : ""  # the subpath of your site, e.g. "/blog"
repository               : "nathan-sunday/nathan-sunday.github.io"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page

# Site Author
author:
  avatar           : "profile.png"
  name             : "Nathan Sunday"
  pronouns         : #"he/him"
  bio              : "PhD Candidate, Department of Economics, University of Michigan"
  location         : "Ann Arbor, Michigan"
  uri              :
  email            : "nsunday@umich.edu"
  cv               : "https://raw.githubusercontent.com/nathan-sunday/Nathan-Sunday-CV/main/CV_NS_2026.pdf"
  bluesky          :
  facebook         :
  foursquare       :
  github           : "nathan-sunday"
  googlescholar   : "https://scholar.google.com/citations?user=Ma4dAkQAAAAJ&hl=en"
  keybase          :
  instagram        :
  impactstory      :
  lastfm           :
  linkedin         : "nathan-sunday-2b385613a"
  mastodon         :
  medium           :
  orcid            :
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Detroit

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
